package net.tradepulse.monitor

data class UiTexts(
  val history: String,
  val settings: String,
  val more: String,
  val scan: String,
  val close: String,
  val settingsHint: String,
  val security: String,
  val email: String,
  val password: String,
  val passwordFirstHint: String,
  val passwordKeepHint: String,
  val symbols: String,
  val symbolsHelp: String,
  val symbolHint: String,
  val add: String,
  val interval: String,
  val intervalHelp: String,
  val lookback: String,
  val lookbackHelp: String,
  val entryScore: String,
  val entryScoreHelp: String,
  val strongScore: String,
  val strongScoreHelp: String,
  val language: String,
  val notifyEntry: String,
  val saveAndStart: String,
  val resultsTitle: String,
  val resultsSubtitle: String,
  val all: String,
  val entry: String,
  val first: String,
  val sell: String,
  val needConfig: String,
  val fillConfigStart: String,
  val settingsHelp: String,
  val noScanResults: String,
  val noFilteredResults: String,
  val scanning: String,
  val testingNetwork: String,
  val pleaseWait: String,
  val startBackground: String,
  val stopBackground: String,
  val testNetwork: String,
  val backgroundStopped: String,
  val scanSuccessBackground: String,
  val scanComplete: String,
  val networkPassed: String,
  val networkFailed: String,
  val gotIt: String,
  val scanFailed: String,
  val languageSaved: String,
  val completeConfigBeforeClose: String,
  val enterSymbol: String,
  val oneSymbolOnly: String,
  val symbolInvalid: String,
  val symbolDuplicate: String,
  val noSymbolsAdded: String,
  val delete: String,
  val firstTag: String,
  val buyScore: String,
  val sellScore: String,
  val price: String,
  val largeDeal: String,
  val recentLargeDeal: String,
  val emailRequired: String,
  val passwordRequired: String,
  val symbolRequired: String,
  val intervalInvalid: String,
  val lookbackInvalid: String,
  val entryScoreInvalid: String,
  val strongScoreInvalid: String,
  val stockCountNeedConfig: String,
  val everyMinutes: String,
  val running: String,
  val failed: String,
  val backgroundRunning: String,
  val backgroundStoppedHeadline: String,
  val waitingFirstScan: String,
  val entryFound: String,
  val sellFound: String,
  val neutral: String,
  val lastScan: String,
  val data: String,
  val noScanYet: String,
  val noSummary: String,
  val historyTitle: String,
  val back: String,
) {
  fun signal(signal: String): String {
    return when (signal) {
      "STRONG_ENTRY" -> if (this === EN) "Strong Entry" else "强入场"
      "MIXED_ENTRY" -> if (this === EN) "Mixed Entry" else "混合入场"
      "POSSIBLE_ENTRY" -> if (this === EN) "Possible Entry" else "可能入场"
      "SELL_PRESSURE" -> if (this === EN) "Sell Pressure" else "卖压"
      "NEUTRAL" -> if (this === EN) "Neutral" else "中性"
      "NO_DATA" -> if (this === EN) "No Data" else "无数据"
      else -> signal
    }
  }

  companion object {
    val ZH = UiTexts(
      history = "历史",
      settings = "设置",
      more = "更多",
      scan = "扫描",
      close = "收起",
      settingsHint = "保存并扫描成功后，配置会自动隐藏。",
      security = "账号密码保存在本机 SharedPreferences。当前版本未启用加密存储。",
      email = "TradePulse 邮箱",
      password = "TradePulse 密码",
      passwordFirstHint = "首次使用请输入密码",
      passwordKeepHint = "留空表示不修改已保存密码",
      symbols = "股票列表",
      symbolsHelp = "一次添加一个股票代码，不需要输入逗号。",
      symbolHint = "例如 AAPL",
      add = "添加",
      interval = "扫描周期（分钟）",
      intervalHelp = "每隔几分钟自动刷新；安卓后台实际执行可能受系统省电影响。",
      lookback = "回看分钟",
      lookbackHelp = "判断最近多少分钟的大单变化，例如 30 表示最近 30 分钟。",
      entryScore = "入场阈值",
      entryScoreHelp = "买入分达到多少算可能入场；默认 45。",
      strongScore = "强入场阈值",
      strongScoreHelp = "买入分达到多少算强入场；默认 70。",
      language = "语言",
      notifyEntry = "首次入场信号发本地通知",
      saveAndStart = "保存并开始监控",
      resultsTitle = "重点结果",
      resultsSubtitle = "优先显示入场和卖压",
      all = "全部",
      entry = "入场",
      first = "首次",
      sell = "卖压",
      needConfig = "需要配置",
      fillConfigStart = "填写账号、密码和股票后开始监控",
      settingsHelp = "点击右上角“设置”，完成配置后首页会只保留核心监控信息。",
      noScanResults = "暂无扫描结果",
      noFilteredResults = "当前筛选下暂无结果",
      scanning = "正在扫描",
      testingNetwork = "正在测试网络",
      pleaseWait = "请稍候...",
      startBackground = "启动后台",
      stopBackground = "停止后台",
      testNetwork = "测试网络",
      backgroundStopped = "后台监控已停止",
      scanSuccessBackground = "扫描成功，后台监控已启动",
      scanComplete = "扫描完成",
      networkPassed = "网络测试通过",
      networkFailed = "网络测试失败",
      gotIt = "知道了",
      scanFailed = "扫描失败",
      languageSaved = "语言已保存",
      completeConfigBeforeClose = "请先完成配置后再收起设置。",
      enterSymbol = "请输入股票代码。",
      oneSymbolOnly = "请一次只添加一个股票代码。",
      symbolInvalid = "股票代码格式不正确。",
      symbolDuplicate = "该股票已添加。",
      noSymbolsAdded = "还没有添加股票。",
      delete = "删除",
      firstTag = "首次",
      buyScore = "买入分",
      sellScore = "卖压分",
      price = "价格",
      largeDeal = "大单净额",
      recentLargeDeal = "最近大单",
      emailRequired = "请填写 TradePulse 邮箱。",
      passwordRequired = "请填写 TradePulse 密码。",
      symbolRequired = "请至少添加一个股票代码。",
      intervalInvalid = "扫描周期必须大于 0。",
      lookbackInvalid = "回看分钟必须大于 0。",
      entryScoreInvalid = "入场阈值必须在 0 到 100 之间。",
      strongScoreInvalid = "强入场阈值必须在 0 到 100 之间。",
      stockCountNeedConfig = "请先完成配置",
      everyMinutes = "每 %d 分钟",
      running = "正在运行",
      failed = "扫描失败",
      backgroundRunning = "后台监控中",
      backgroundStoppedHeadline = "后台已停止",
      waitingFirstScan = "等待首次扫描",
      entryFound = "发现入场信号",
      sellFound = "存在卖压",
      neutral = "暂无明显信号",
      lastScan = "最近扫描",
      data = "数据",
      noScanYet = "尚未扫描",
      noSummary = "还没有扫描结果，点击“扫描”获取最新数据。",
      historyTitle = "历史记录",
      back = "返回",
    )

    val EN = UiTexts(
      history = "History",
      settings = "Settings",
      more = "More",
      scan = "Scan",
      close = "Hide",
      settingsHint = "Settings will hide after a successful save and scan.",
      security = "Account credentials are stored locally in SharedPreferences. Encryption is not enabled yet.",
      email = "TradePulse Email",
      password = "TradePulse Password",
      passwordFirstHint = "Enter password",
      passwordKeepHint = "Leave blank to keep saved password",
      symbols = "Symbols",
      symbolsHelp = "Add one symbol at a time. Do not use commas.",
      symbolHint = "e.g. AAPL",
      add = "Add",
      interval = "Scan Interval (minutes)",
      intervalHelp = "Automatic refresh interval. Android background timing may be affected by battery settings.",
      lookback = "Lookback Minutes",
      lookbackHelp = "Recent large-deal window, for example 30 means the latest 30 minutes.",
      entryScore = "Entry Threshold",
      entryScoreHelp = "Minimum buy score for possible entry. Default 45.",
      strongScore = "Strong Entry Threshold",
      strongScoreHelp = "Minimum buy score for strong entry. Default 70.",
      language = "Language",
      notifyEntry = "Send local notification for first entry signals",
      saveAndStart = "Save and Start",
      resultsTitle = "Key Results",
      resultsSubtitle = "Entry and sell pressure first",
      all = "All",
      entry = "Entry",
      first = "First",
      sell = "Sell",
      needConfig = "Setup Needed",
      fillConfigStart = "Enter account, password, and symbols to start monitoring",
      settingsHelp = "Open Settings to finish setup. After that the home screen will focus on monitoring.",
      noScanResults = "No scan results",
      noFilteredResults = "No results for this filter",
      scanning = "Scanning",
      testingNetwork = "Testing network",
      pleaseWait = "Please wait...",
      startBackground = "Start Background",
      stopBackground = "Stop Background",
      testNetwork = "Test Network",
      backgroundStopped = "Background monitoring stopped",
      scanSuccessBackground = "Scan succeeded. Background monitoring started",
      scanComplete = "Scan complete",
      networkPassed = "Network test passed",
      networkFailed = "Network test failed",
      gotIt = "OK",
      scanFailed = "Scan failed",
      languageSaved = "Language saved",
      completeConfigBeforeClose = "Finish setup before hiding settings.",
      enterSymbol = "Enter a symbol.",
      oneSymbolOnly = "Add only one symbol at a time.",
      symbolInvalid = "Invalid symbol format.",
      symbolDuplicate = "This symbol already exists.",
      noSymbolsAdded = "No symbols added.",
      delete = "Delete",
      firstTag = "First",
      buyScore = "Buy Score",
      sellScore = "Sell Score",
      price = "Price",
      largeDeal = "Large Deal Net",
      recentLargeDeal = "Recent Large Deal",
      emailRequired = "TradePulse email is required.",
      passwordRequired = "TradePulse password is required.",
      symbolRequired = "At least one symbol is required.",
      intervalInvalid = "Scan interval must be greater than 0.",
      lookbackInvalid = "Lookback minutes must be greater than 0.",
      entryScoreInvalid = "Entry threshold must be between 0 and 100.",
      strongScoreInvalid = "Strong entry threshold must be between 0 and 100.",
      stockCountNeedConfig = "Setup needed",
      everyMinutes = "Every %d min",
      running = "Running",
      failed = "Scan Failed",
      backgroundRunning = "Background Running",
      backgroundStoppedHeadline = "Background Stopped",
      waitingFirstScan = "Waiting for First Scan",
      entryFound = "Entry Signal Found",
      sellFound = "Sell Pressure Found",
      neutral = "No Clear Signal",
      lastScan = "Last scan",
      data = "Data",
      noScanYet = "No scan yet",
      noSummary = "No scan result yet. Tap Scan to fetch the latest data.",
      historyTitle = "History",
      back = "Back",
    )
  }
}

fun uiTexts(language: String): UiTexts = if (language == "en-US") UiTexts.EN else UiTexts.ZH
